#!/bin/bash


#SDKPATH=$HOME/Android/sdk
#ANDROJAR=$SDKPATH/platforms/android-4.0.3/android.jar
ANDROJAR=/usr/local/android/sdk/platforms/android-4.1.1/android.jar
# PATH=$SDKPATH/tools:$SDKPATH/platform-tools:$PATH

perl -i settime.pl res/values/strings.xml 
perl -i settime.pl res/values-ru/strings.xml 

# will output *.java files to net/avs234
aidl -Isrc -o. src/net/avs234/alsaplayer/IAndLessSrv.aidl
aidl -Isrc -o. src/net/avs234/alsaplayer/IAndLessSrvCallback.aidl

echo "packing"
aapt package -f -M AndroidManifest.xml -I $ANDROJAR -F net/resources.bin -S res -J net/avs234/alsaplayer

echo "compiling"
# javac will output to net/avs234 hierarchy
javac -g:none -cp $ANDROJAR -d . net/avs234/alsaplayer/*.java src/net/avs234/alsaplayer/iconifiedlist/*.java src/net/avs234/alsaplayer/*.java

echo "running dx"
dx --dex --output=net/classes.dex net/avs234/alsaplayer/*.class net/avs234/alsaplayer/iconifiedlist/*.class

echo "running builder"
apkbuilder tmp.apk -u -z net/resources.bin -f net/classes.dex -nf libs


ALIAS=cert
PASS=verybadpassword
keytool -genkey -keystore net/cert.keystore -alias $ALIAS -keyalg RSA -keysize 512 -validity 20000 \
     -keypass $PASS -storepass $PASS  -dname "cn=nobody, ou=none, o=none, c=US"

jarsigner -keystore net/cert.keystore -keypass $PASS -storepass $PASS -signedjar tmp-signed.apk tmp.apk $ALIAS

rm -f alsaplayer.apk 

zipalign 4 tmp-signed.apk alsaplayer.apk

rm -rf net tmp-signed.apk tmp.apk


